#!/usr/bin/env python3
"""
diff_worksheet_template.py

Compare two TTPOST courier worksheets cell-by-cell and emit a markdown diff
report. Designed to compare the canonical golden template against a worksheet
generated by `courier_export.build_worksheet_v3`.

Usage:
    python3 scripts/diff_worksheet_template.py golden.xlsx generated.xlsx
    python3 scripts/diff_worksheet_template.py golden.xlsx generated.xlsx --json
"""
from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Dict, List, Optional, Tuple

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet


# ── Style normalization ──────────────────────────────────────────────────────


def _font_signature(font) -> Dict[str, Any]:
    """Reduce a Font object to a comparable dict."""
    if not font:
        return {}
    return {
        "name": font.name,
        "size": font.size,
        "bold": bool(font.bold),
        "italic": bool(font.italic),
        "color": getattr(getattr(font, "color", None), "rgb", None),
    }


def _alignment_signature(alignment) -> Dict[str, Any]:
    if not alignment:
        return {}
    return {
        "horizontal": alignment.horizontal,
        "vertical": alignment.vertical,
        "wrap_text": bool(alignment.wrap_text),
    }


def _fill_signature(fill) -> Dict[str, Any]:
    if not fill:
        return {}
    fg = getattr(getattr(fill, "fgColor", None), "rgb", None)
    return {
        "pattern_type": fill.patternType,
        "fg_color": fg,
    }


def _border_signature(border) -> Dict[str, Any]:
    if not border:
        return {}
    out = {}
    for side in ("left", "right", "top", "bottom"):
        s = getattr(border, side, None)
        if s and s.style:
            out[side] = s.style
    return out


def cell_signature(cell) -> Dict[str, Any]:
    """Return a comparable dict of a cell's value + style."""
    return {
        "value": cell.value,
        "data_type": cell.data_type,
        "number_format": cell.number_format,
        "font": _font_signature(cell.font),
        "alignment": _alignment_signature(cell.alignment),
        "fill": _fill_signature(cell.fill),
        "border": _border_signature(cell.border),
    }


# ── Sheet-level extraction ───────────────────────────────────────────────────


def extract_sheet_info(ws: Worksheet) -> Dict[str, Any]:
    """Pull merged ranges, column widths, row heights, and a cell matrix."""
    info: Dict[str, Any] = {
        "name": ws.title,
        "max_row": ws.max_row,
        "max_col": ws.max_column,
        "merged_ranges": sorted(str(r) for r in ws.merged_cells.ranges),
        "column_widths": {},
        "row_heights": {},
        "cells": {},
    }

    # Column widths
    for letter, col_dim in ws.column_dimensions.items():
        if col_dim.width is not None:
            info["column_widths"][letter] = round(col_dim.width, 2)

    # Row heights
    for row_idx, row_dim in ws.row_dimensions.items():
        if row_dim.height is not None:
            info["row_heights"][row_idx] = round(row_dim.height, 2)

    # Cell content + style
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None and cell.data_type == "n":
                continue
            ref = cell.coordinate
            info["cells"][ref] = cell_signature(cell)

    return info


# ── Diff logic ───────────────────────────────────────────────────────────────


def diff_dicts(label: str, a: Dict[str, Any], b: Dict[str, Any],
               tolerance: float = 0.0) -> List[str]:
    """Report keys that differ between two dicts."""
    differences = []
    all_keys = set(a) | set(b)
    for k in sorted(all_keys, key=lambda x: (isinstance(x, str), x)):
        va = a.get(k)
        vb = b.get(k)
        if va == vb:
            continue
        if isinstance(va, (int, float)) and isinstance(vb, (int, float)) and tolerance > 0:
            if abs(va - vb) <= tolerance:
                continue
        differences.append(f"{label}[{k}]: golden={va!r} generated={vb!r}")
    return differences


def diff_cell(ref: str, a: Dict, b: Dict) -> List[str]:
    """Report cell-level differences."""
    diffs = []
    for key in ("value", "number_format"):
        if a.get(key) != b.get(key):
            diffs.append(f"  {ref}.{key}: golden={a.get(key)!r} generated={b.get(key)!r}")
    # Compare styles
    for style_key in ("font", "alignment", "fill", "border"):
        ad = a.get(style_key) or {}
        bd = b.get(style_key) or {}
        for k in set(ad) | set(bd):
            if ad.get(k) != bd.get(k):
                diffs.append(f"  {ref}.{style_key}.{k}: golden={ad.get(k)!r} generated={bd.get(k)!r}")
    return diffs


def build_report(golden: Dict[str, Any], generated: Dict[str, Any]) -> Dict[str, Any]:
    """Build a structured diff report."""
    report: Dict[str, Any] = {
        "summary": {
            "golden_dim": f"{golden['max_row']}x{golden['max_col']}",
            "generated_dim": f"{generated['max_row']}x{generated['max_col']}",
            "golden_merged_count": len(golden["merged_ranges"]),
            "generated_merged_count": len(generated["merged_ranges"]),
            "golden_cells_with_content": len(golden["cells"]),
            "generated_cells_with_content": len(generated["cells"]),
        },
        "merged_ranges_diff": {
            "only_in_golden": sorted(set(golden["merged_ranges"]) - set(generated["merged_ranges"])),
            "only_in_generated": sorted(set(generated["merged_ranges"]) - set(golden["merged_ranges"])),
        },
        "column_widths_diff": diff_dicts("column_widths",
                                          golden["column_widths"],
                                          generated["column_widths"],
                                          tolerance=0.5),
        "row_heights_diff": diff_dicts("row_heights",
                                        golden["row_heights"],
                                        generated["row_heights"],
                                        tolerance=1.0),
        "cell_diffs": [],
        "cells_only_in_golden": [],
        "cells_only_in_generated": [],
    }

    all_refs = set(golden["cells"]) | set(generated["cells"])
    for ref in sorted(all_refs, key=lambda r: (int("".join(c for c in r if c.isdigit()) or 0),
                                                "".join(c for c in r if c.isalpha()))):
        ga = golden["cells"].get(ref)
        gb = generated["cells"].get(ref)
        if ga is None:
            report["cells_only_in_generated"].append({"ref": ref, "content": gb.get("value")})
            continue
        if gb is None:
            report["cells_only_in_golden"].append({"ref": ref, "content": ga.get("value")})
            continue
        d = diff_cell(ref, ga, gb)
        if d:
            report["cell_diffs"].append({"ref": ref, "differences": d})

    return report


def format_markdown_report(report: Dict[str, Any]) -> str:
    """Render the diff report as markdown."""
    out = ["# Worksheet template diff report\n"]

    # Summary
    s = report["summary"]
    out.append("## Summary\n")
    out.append(f"| | Golden | Generated |\n")
    out.append(f"|---|---|---|\n")
    out.append(f"| Dimensions | {s['golden_dim']} | {s['generated_dim']} |\n")
    out.append(f"| Merged ranges | {s['golden_merged_count']} | {s['generated_merged_count']} |\n")
    out.append(f"| Cells with content | {s['golden_cells_with_content']} | {s['generated_cells_with_content']} |\n")
    out.append("")

    # Merged ranges
    mr = report["merged_ranges_diff"]
    if mr["only_in_golden"] or mr["only_in_generated"]:
        out.append("## Merged-range differences\n")
        if mr["only_in_golden"]:
            out.append("**Only in golden** (missing in generated):\n")
            for r in mr["only_in_golden"]:
                out.append(f"- `{r}`")
            out.append("")
        if mr["only_in_generated"]:
            out.append("**Only in generated** (extra):\n")
            for r in mr["only_in_generated"]:
                out.append(f"- `{r}`")
            out.append("")

    # Column widths
    if report["column_widths_diff"]:
        out.append("## Column-width differences\n")
        for d in report["column_widths_diff"]:
            out.append(f"- {d}")
        out.append("")

    # Row heights
    if report["row_heights_diff"]:
        out.append("## Row-height differences\n")
        for d in report["row_heights_diff"]:
            out.append(f"- {d}")
        out.append("")

    # Cells only in golden
    if report["cells_only_in_golden"]:
        out.append(f"## Cells present in golden but missing in generated ({len(report['cells_only_in_golden'])})\n")
        for item in report["cells_only_in_golden"][:50]:
            v = item["content"]
            if isinstance(v, str) and len(v) > 60:
                v = v[:60] + "…"
            out.append(f"- `{item['ref']}`: {v!r}")
        if len(report["cells_only_in_golden"]) > 50:
            out.append(f"- *(+{len(report['cells_only_in_golden']) - 50} more)*")
        out.append("")

    # Cells only in generated
    if report["cells_only_in_generated"]:
        out.append(f"## Cells present in generated but not in golden ({len(report['cells_only_in_generated'])})\n")
        for item in report["cells_only_in_generated"][:50]:
            v = item["content"]
            if isinstance(v, str) and len(v) > 60:
                v = v[:60] + "…"
            out.append(f"- `{item['ref']}`: {v!r}")
        if len(report["cells_only_in_generated"]) > 50:
            out.append(f"- *(+{len(report['cells_only_in_generated']) - 50} more)*")
        out.append("")

    # Cell differences
    if report["cell_diffs"]:
        out.append(f"## Cells present in both but with differences ({len(report['cell_diffs'])})\n")
        for item in report["cell_diffs"][:60]:
            out.append(f"### `{item['ref']}`\n")
            for d in item["differences"]:
                out.append(d)
            out.append("")
        if len(report["cell_diffs"]) > 60:
            out.append(f"*(+{len(report['cell_diffs']) - 60} more cells with differences)*")
            out.append("")

    return "\n".join(out)


# ── Entrypoint ───────────────────────────────────────────────────────────────


def main():
    p = argparse.ArgumentParser(description="Diff two worksheet XLSX files")
    p.add_argument("golden", help="Path to golden template")
    p.add_argument("generated", help="Path to generated worksheet")
    p.add_argument("--json", action="store_true", help="Emit JSON instead of markdown")
    p.add_argument("--sheet", default=None, help="Sheet name (default: active)")
    args = p.parse_args()

    g_wb = load_workbook(args.golden, data_only=False)
    g_ws = g_wb[args.sheet] if args.sheet else g_wb.active

    x_wb = load_workbook(args.generated, data_only=False)
    x_ws = x_wb[args.sheet] if args.sheet else x_wb.active

    g_info = extract_sheet_info(g_ws)
    x_info = extract_sheet_info(x_ws)
    report = build_report(g_info, x_info)

    if args.json:
        print(json.dumps(report, indent=2, default=str))
    else:
        print(format_markdown_report(report))


if __name__ == "__main__":
    main()
